# Dockerfile.model-training
FROM python:3.10.8-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt


COPY static/ ./static/
COPY templates/ ./templates/

EXPOSE 5000
COPY app.py .
CMD ["python", "app.py"]
