version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: NewDB
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "5050:80"

  todoapp:
    container_name: app_container
    image: aloysias/todoapp:latest
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:12345@db:5432/NewDB"
    ports:
      - "5000:5000"
    depends_on:
      - db